app:
  last_open_dir: .
path:
  osu_path: C:/MyOtherFiles/osu!/Songs/MetaHumanBoi - kinetic flux/MetaHumanBoi -
    kinetic flux (mintIceCream_) [Expert].osu
  output_path: C:/MyOtherFiles/DEV/osb-render/output.mp4
renderer:
  crf: 20
  enable_audio: true
  encoder_preset: fast
  fps: 60
  height: 720
  sample_method: linear
  use_gpu: true
  width: 1280
